name: GSIBerror
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - jupyter_core
  - jupyter_client
  - matplotlib
  - notebook
  - numpy>=1.20.3
  - pip
  - python=3.8.2
  - xarray
  - pip:
    - -e.  
