# Project information
site_name: GSIBerror
site_author: Carlos Frederico Bastarz
site_description: Site com a documentação e exemplos de uso do GSIBerror

# Repository
repo_name: cfbastarz/GSIBerror
repo_url: https://github.com/cfbastarz/GSIBerror
edit_uri: edit/master/docs/

# Page tree
nav:
  - 'Instalação': instalacao.md
  - 'Uso': uso_gsiberror.md

#Configuration
theme: 
  name: material
  language: pt-BR
  features:
    - content.tabs.link
#    - navigation.instant
#    - navigation.tracking
#    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.sections
#    - navigation.top
#  name: readthedocs
#  palette:
#    scheme: slate

extra:
    social:
      - icon: fontawesome/brands/youtube
        link: https://www.youtube.com/channel/UCYtOSAm2NlYArmPwUkg1kUw
      - icon: fontawesome/brands/github
        link: https://github.com/cfbastarz
      - icon: fontawesome/solid/paper-plane
        link: mailto:cfbastarz@gmail.com

# Extensions
markdown_extensions:
  - footnotes
  - tables
  - admonition
  - abbr
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - attr_list
#  - pymdownx.emoji:
#      emoji_index: !!python/name:materialx.emoji.twemoji
#      emoji_generator: !!python/name:materialx.emoji.to_svg

#extra_javascript:
#  - javascripts/mathjax.js
#  - https://polyfill.io/v3/polyfill.min.js?features=es6
#  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Plugins
plugins:
  - mkdocs-video
  - search
#  - with-pdf
#  - mkdocs-jupyter
#  - mkdocs-jupyter:
#      theme: dark
