# Project information
site_name: GSIBerror
site_author: Carlos Frederico Bastarz
site_description: A Python class to access, read and plot information from the background error covariance matrix from the GSI (Gridpoint Statistical Interpolation)

# Repository
repo_name: GAD-DIMNT-CPTEC/GSIBerror
repo_url: https://github.com/GAD-DIMNT-CPTEC/GSIBerror
edit_uri: edit/main/docs/

# Page tree
nav:
  - English:
    - index.md
    - Installation: en/install.md
    - Usage: en/usage.md
  - Português:
    - GSIBerror: pt/index.md
    - Instalação: pt/instalacao.md
    - Uso: pt/uso.md

#Configuration
theme: 
  name: material
  language: pt-BR
  palette:
    primary: light blue
    accent: light blue
  features:
#    - content.tabs.link
#    - navigation.instant
#    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.sections
#    - navigation.top
#  name: readthedocs
#  palette:
#    scheme: slate

extra:
    social:
      - icon: fontawesome/brands/youtube
        link: https://www.youtube.com/channel/UCYtOSAm2NlYArmPwUkg1kUw
      - icon: fontawesome/brands/github
        link: https://github.com/cfbastarz
      - icon: fontawesome/solid/paper-plane
        link: mailto:cfbastarz@gmail.com

# Extensions
markdown_extensions:
  - footnotes
  - tables
  - admonition
  - abbr
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
#  - pymdownx.emoji:
#      emoji_index: !!python/name:materialx.emoji.twemoji
#      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Plugins
plugins:
  - mkdocs-video
  - search
    #  - mkdocs_pymdownx_material_extras
#  - with-pdf
#  - mkdocs-jupyter
#  - mkdocs-jupyter:
#      theme: dark
