name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: setup.py
      - run: pip install -e ".[dev]"
      - run: ruff check . --exclude notebooks
      - run: ruff format --check gsiberror tests setup.py
      - run: pytest

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x 
      - run: pip install mkdocs-material 
      - run: pip install mkdocs-video
      - run: pip install mkdocs-pdf-export-plugin
      - run: pip install mkdocs-jupyter
      - run: mkdocs gh-deploy --force
